# Generated by Django 5.2.5 on 2026-07-16 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Məbləğ')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ödənilən məbləğ')),
                ('currency', models.CharField(default='AZN', max_length=3, verbose_name='Valyuta')),
                ('payment_method', models.CharField(choices=[('cash', 'Nağd'), ('card', 'Kart'), ('bank_transfer', 'Bank köçürməsi'), ('pos', 'POS'), ('other', 'Digər')], default='cash', max_length=20, verbose_name='Ödəniş üsulu')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ödəniş tarixi')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Son tarix')),
                ('installment_number', models.IntegerField(default=1, verbose_name='Hissə nömrəsi')),
                ('total_installments', models.IntegerField(default=1, verbose_name='Ümumi hissə')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('receipt_number', models.CharField(blank=True, max_length=100, verbose_name='Qəbiz nömrəsi')),
                ('status', models.CharField(choices=[('pending', 'Gözləyir'), ('paid', 'Ödənilib'), ('overdue', 'Gecikmiş'), ('cancelled', 'Ləğv olunub'), ('refunded', 'Geri qaytarılıb')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Qeydlər')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_payments', to=settings.AUTH_USER_MODEL, verbose_name='Toplayan')),
                ('groups', models.ManyToManyField(blank=True, related_name='payments', to='courses.group', verbose_name='Qruplar')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student', verbose_name='Tələbə')),
            ],
            options={
                'verbose_name': 'Ödəniş',
                'verbose_name_plural': 'Ödənişlər',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ümumi məbləğ')),
                ('total_installments', models.IntegerField(verbose_name='Ümumi hissə')),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Hissə məbləği')),
                ('start_date', models.DateField(verbose_name='Başlama tarixi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='courses.group', verbose_name='Qrup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='students.student', verbose_name='Tələbə')),
            ],
            options={
                'verbose_name': 'Ödəniş planı',
                'verbose_name_plural': 'Ödəniş planları',
                'ordering': ('-created_at',),
            },
        ),
    ]
