# Generated by Django 5.2.5 on 2026-07-10 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='payment date')),
                ('payment_method', models.CharField(choices=[('cash', 'Nağd'), ('card', 'Kart'), ('transfer', 'Bank köçürməsi'), ('other', 'Digər')], default='cash', max_length=20, verbose_name='method')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='courses.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ('-payment_date',),
            },
        ),
    ]
