# Generated by Django 5.2.5 on 2026-07-29 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('students', '0003_student_academic_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Ay')),
                ('year', models.IntegerField(verbose_name='İl')),
                ('status', models.CharField(choices=[('not_paid', 'Ödənməyib'), ('paid', 'Ödənilib'), ('overdue', 'Gecikib')], default='not_paid', max_length=20, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Məbləğ')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Ödənmə tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_payments', to='students.student', verbose_name='Tələbə')),
            ],
            options={
                'verbose_name': 'Aylıq ödəniş',
                'verbose_name_plural': 'Aylıq ödənişlər',
                'ordering': ('year', 'month'),
                'unique_together': {('student', 'month', 'year')},
            },
        ),
    ]
