# Generated by Django 5.2.5 on 2026-07-10 08:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockipadress',
            options={'verbose_name': 'Bloklanmış IP', 'verbose_name_plural': 'Bloklanmış IP-lər'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'İstifadəçi', 'verbose_name_plural': 'İstifadəçilər'},
        ),
        migrations.AlterField(
            model_name='blockipadress',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP ünvanı'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Bioqrafiya'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email ünvanı'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ips',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(), blank=True, null=True, size=None, verbose_name='IP ünvanları'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/', verbose_name='Şəkil'),
        ),
    ]
