# Generated by Django 5.2.5 on 2026-07-16 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('occupation', models.CharField(blank=True, max_length=200, verbose_name='Peşə')),
                ('address', models.TextField(blank=True, verbose_name='Ünvan')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Əsas əlaqə')),
                ('notes', models.TextField(blank=True, verbose_name='Qeydlər')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Valideyn',
                'verbose_name_plural': 'Valideynlər',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Tələbə ID')),
                ('parent_phone', models.CharField(blank=True, max_length=50, verbose_name='Valideyn telefonu')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Doğum tarixi')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Kişi'), ('female', 'Qadın')], max_length=10, verbose_name='Cins')),
                ('address', models.TextField(blank=True, verbose_name='Ünvan')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('emergency_phone', models.CharField(blank=True, max_length=50, verbose_name='Təcili telefon')),
                ('school', models.CharField(blank=True, max_length=200, verbose_name='Məktəb')),
                ('grade_level', models.CharField(blank=True, max_length=20, verbose_name='Sinif')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('frozen', 'Dondurulmuş'), ('graduated', 'Məzun'), ('transferred', 'Köçürülmüş'), ('dropped', 'Ayrılıb')], default='active', max_length=20, verbose_name='Status')),
                ('enrollment_date', models.DateField(blank=True, null=True, verbose_name='Qeydiyyat tarixi')),
                ('notes', models.TextField(blank=True, verbose_name='Qeydlər')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Aylıq ödəniş')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Endirim (AZN)')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='Son ödəniş tarixi')),
                ('payment_status', models.CharField(choices=[('none', 'Məlumat yoxdur'), ('pending', 'Gözləyir'), ('up_to_date', 'Borcu yoxdur'), ('overdue', 'Gecikmiş')], default='none', max_length=20, verbose_name='Ödəniş statusu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='students.parent', verbose_name='Valideyn')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Tələbə',
                'verbose_name_plural': 'Tələbələr',
                'ordering': ('-created_at',),
            },
        ),
    ]
