# Generated by Django 5.2.5 on 2026-07-29 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_group_course'),
        ('students', '0002_student_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='courses.academicyear', verbose_name='Tədris ili'),
        ),
    ]
