# Generated by Django 5.2.5 on 2026-08-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='work_number',
            field=models.PositiveIntegerField(blank=True, help_text='Nəticə axtarışı üçün 5 rəqəmli iş nömrəsi. Avtomatik yaradılır.', null=True, unique=True, verbose_name='İş nömrəsi'),
        ),
    ]
