# Generated by Django 5.2.5 on 2026-07-16 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
            ],
            options={
                'verbose_name': 'Vəzifə',
                'verbose_name_plural': 'Vəzifələr',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True, verbose_name='İşçi ID')),
                ('department', models.CharField(choices=[('academic', 'Akademik'), ('finance', 'Maliyyə'), ('hr', 'HR'), ('marketing', 'Marketinq'), ('reception', 'Resepsiyon'), ('management', 'İdarəetmə'), ('other', 'Digər')], default='other', max_length=100, verbose_name='Şöbə')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='İşə başlama tarixi')),
                ('salary_type', models.CharField(choices=[('fixed', 'Sabit maaş'), ('per_student', 'Tələbə sayına görə')], default='fixed', max_length=20, verbose_name='Maaş növü')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sabit maaş')),
                ('salary_per_student', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tələbə başına məbləğ')),
                ('salary_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tələbə başına faiz')),
                ('salary_currency', models.CharField(default='AZN', max_length=3, verbose_name='Valyuta')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='Bank hesabı')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='VÖEN')),
                ('emergency_contact', models.JSONField(blank=True, default=dict, verbose_name='Təcili əlaqə')),
                ('documents', models.JSONField(blank=True, default=list, verbose_name='Sənədlər')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
                ('position_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.position', verbose_name='Vəzifə')),
            ],
            options={
                'verbose_name': 'İşçi',
                'verbose_name_plural': 'İşçilər',
                'ordering': ('-created_at',),
            },
        ),
    ]
