# Generated by Django 5.2.5 on 2025-09-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(unique=True, verbose_name='message'),
        ),
    ]
