# Generated by Django 5.2.5 on 2026-07-16 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='Başlıq')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('exam_type', models.CharField(choices=[('abiturient', 'Abituriyent'), ('entrance', 'Qəbul imtahanı'), ('placement', 'Yerləşdirmə imtahanı'), ('course', 'Kurs imtahanı'), ('competition', 'Sınaq/Südüş')], max_length=20, verbose_name='İmtahan növü')),
                ('status', models.CharField(choices=[('draft', 'Qaralama'), ('published', 'Dərc olunmuş'), ('active', 'Aktiv'), ('completed', 'Bitmiş'), ('archived', 'Arxivlənmiş')], default='draft', max_length=20, verbose_name='Status')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Fənn')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Ümumi sual sayı')),
                ('total_time_minutes', models.IntegerField(default=0, verbose_name='Müddət (dəqiqə)')),
                ('passing_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Keçid balı')),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Maksimum bal')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Başlama tarixi')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Bitmə tarixi')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Qeydiyyat son tarixi')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qiymət')),
                ('max_participants', models.IntegerField(default=0, verbose_name='Maksimum iştirakçı')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Məkan')),
                ('allow_variant_selection', models.BooleanField(default=True, verbose_name='Variant seçiminə icazə')),
                ('shuffle_questions', models.BooleanField(default=True, verbose_name='Sualları qarışdır')),
                ('shuffle_options', models.BooleanField(default=True, verbose_name='Seçimləri qarışdır')),
                ('show_results_immediately', models.BooleanField(default=False, verbose_name='Nəticələri dərhal göstər')),
                ('allow_review', models.BooleanField(default=True, verbose_name='Baxışa icazə')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_exams', to='courses.course', verbose_name='Kurs')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='Yaradan')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_exams', to='courses.group', verbose_name='Qrup')),
            ],
            options={
                'verbose_name': 'İmtahan',
                'verbose_name_plural': 'İmtahanlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='Başlıq')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('status', models.CharField(choices=[('draft', 'Qaralama'), ('active', 'Aktiv'), ('completed', 'Bitmiş')], default='draft', max_length=20, verbose_name='Status')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Başlama tarixi')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Bitmə tarixi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('exams', models.ManyToManyField(blank=True, related_name='competitions', to='exam_system.exam', verbose_name='İmtahanlar')),
            ],
            options={
                'verbose_name': 'Sınaq/Südüş',
                'verbose_name_plural': 'Sınaqlar/Südüşlər',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('single_choice', 'Tək seçimli'), ('multiple_choice', 'Çox seçimli'), ('true_false', 'Doğru/Yanlış'), ('text', 'Mətn'), ('matching', 'Uyğunluq'), ('ordering', 'Sıralama')], max_length=20, verbose_name='Sual növü')),
                ('text', models.TextField(verbose_name='Sual mətni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exam_questions/', verbose_name='Şəkil')),
                ('answers_data', models.JSONField(blank=True, default=dict, help_text='JSON formatında cavab variantları. Nümunə: {"options": [{"id": "a", "text": "...", "is_correct": true}, ...], "correct_text": "..."}', verbose_name='Cavablar (JSON)')),
                ('difficulty', models.IntegerField(choices=[(1, 'Asan'), (2, 'Orta'), (3, 'Çətin'), (4, 'Ekspert')], default=2, verbose_name='Çətinlik')),
                ('points', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Ball')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('explanation', models.TextField(blank=True, verbose_name='Açıqlama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam_system.exam', verbose_name='İmtahan')),
            ],
            options={
                'verbose_name': 'Sual',
                'verbose_name_plural': 'Suallar',
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_option_ids', models.JSONField(blank=True, default=list, verbose_name='Seçilmiş cavablar')),
                ('text_answer', models.TextField(blank=True, verbose_name='Mətn cavabı')),
                ('matching_data', models.JSONField(blank=True, default=dict, verbose_name='Uyğunluq məlumatı')),
                ('ordering_data', models.JSONField(blank=True, default=list, verbose_name='Sıralama məlumatı')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Doğrudur')),
                ('points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Qazanılan bal')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Cavablandırma vaxtı')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='exam_system.question', verbose_name='Sual')),
            ],
            options={
                'verbose_name': 'Tələbə cavabı',
                'verbose_name_plural': 'Tələbə cavabları',
                'ordering': ('answered_at',),
            },
        ),
        migrations.CreateModel(
            name='MarkerConsensus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marker1_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Marker 1 balı')),
                ('marker1_notes', models.TextField(blank=True, verbose_name='Marker 1 qeydləri')),
                ('marker2_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Marker 2 balı')),
                ('marker2_notes', models.TextField(blank=True, verbose_name='Marker 2 qeydləri')),
                ('marker3_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Marker 3 balı')),
                ('marker3_notes', models.TextField(blank=True, verbose_name='Marker 3 qeydləri')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Yekun bal')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Həll olunub')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('marker1_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marker1_consensus', to=settings.AUTH_USER_MODEL, verbose_name='Marker 1')),
                ('marker2_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marker2_consensus', to=settings.AUTH_USER_MODEL, verbose_name='Marker 2')),
                ('marker3_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marker3_consensus', to=settings.AUTH_USER_MODEL, verbose_name='Marker 3')),
                ('student_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marker_consensus', to='exam_system.studentanswer', verbose_name='Tələbə cavabı')),
            ],
            options={
                'verbose_name': 'Marker konsensusu',
                'verbose_name_plural': 'Marker konsensusları',
            },
        ),
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('registered', 'Qeydiyyatdan keçib'), ('in_progress', 'Davam edir'), ('completed', 'Bitirib'), ('cancelled', 'Ləğv olunub')], default='registered', max_length=20, verbose_name='Status')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Bal')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Faiz')),
                ('passed', models.BooleanField(blank=True, null=True, verbose_name='Keçib')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Başlama vaxtı')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitirmə vaxtı')),
                ('time_spent_seconds', models.IntegerField(default=0, verbose_name='Xərclənən vaxt (saniyə)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP ünvanı')),
                ('user_agent', models.TextField(blank=True, verbose_name='Brauzer məlumatı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exams', to='exam_system.exam', verbose_name='İmtahan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exams', to='students.student', verbose_name='Tələbə')),
            ],
            options={
                'verbose_name': 'Tələbə imtahanı',
                'verbose_name_plural': 'Tələbə imtahanları',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='student_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam_system.studentexam', verbose_name='İmtahan'),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('code', models.CharField(max_length=50, verbose_name='Kod')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='exam_system.exam', verbose_name='İmtahan')),
                ('questions', models.ManyToManyField(blank=True, related_name='variants', to='exam_system.question', verbose_name='Suallar')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variantlar',
                'ordering': ('sort_order', 'name'),
                'unique_together': {('exam', 'code')},
            },
        ),
        migrations.AddField(
            model_name='studentexam',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_exams', to='exam_system.variant', verbose_name='Variant'),
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('student_exam', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='studentexam',
            unique_together={('exam', 'student')},
        ),
    ]
