# Generated by Django 5.2.5 on 2026-08-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='dim_type',
            field=models.CharField(blank=True, choices=[('buraxilis', 'Buraxılış'), ('blok', 'Blok')], help_text='DİM bal sistemi ilə hesablanan imtahanlar üçün', max_length=20, verbose_name='DİM növü'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_group',
            field=models.CharField(blank=True, choices=[('1', 'I qrup'), ('2', 'II qrup'), ('3', 'III qrup'), ('4', 'IV qrup')], max_length=2, verbose_name='Qrup'),
        ),
        migrations.AddField(
            model_name='exam',
            name='group_subtype',
            field=models.CharField(blank=True, choices=[('', 'Standart'), ('ri', 'Rİ'), ('rk', 'RK'), ('tc', 'TC'), ('dt', 'DT')], max_length=10, verbose_name='Alt növ'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sual nömrəsi'),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fənn'),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='dim_max_bal',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='DİM maksimal bal'),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='dim_result',
            field=models.JSONField(blank=True, default=dict, verbose_name='DİM nəticəsi'),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='dim_total_bal',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='DİM ümumi bal'),
        ),
    ]
