# Generated by Django 5.2.5 on 2026-07-16 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('teacher_id', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Müəllim ID')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='İxtisas')),
                ('bio', models.TextField(blank=True, verbose_name='Bioqrafiya')),
                ('education', models.JSONField(blank=True, default=list, verbose_name='Təhsil')),
                ('certificates', models.JSONField(blank=True, default=list, verbose_name='Sertifikatlar')),
                ('subjects', models.JSONField(blank=True, default=list, verbose_name='Fənlər')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saatlıq tarif')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to='employees.employee', verbose_name='İşçi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Müəllim',
                'verbose_name_plural': 'Müəllimlər',
                'ordering': ('-created_at',),
            },
        ),
    ]
