# Generated by Django 5.2.5 on 2026-07-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum tarixi'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ata adı'),
        ),
    ]
