# Generated by Django 5.2.5 on 2026-07-16 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('monday', 'Bazar ertəsi'), ('tuesday', 'Çərşənbə axşamı'), ('wednesday', 'Çərşənbə'), ('thursday', 'Cümə axşamı'), ('friday', 'Cümə'), ('saturday', 'Şənbə'), ('sunday', 'Bazar')], max_length=20, verbose_name='Həftənin günü')),
                ('start_time', models.TimeField(verbose_name='Başlama vaxtı')),
                ('end_time', models.TimeField(verbose_name='Bitmə vaxtı')),
                ('lesson_duration', models.IntegerField(default=60, verbose_name='Dərs müddəti (dəq)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.group', verbose_name='Qrup')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='teachers.teacher', verbose_name='Müəllim')),
            ],
            options={
                'verbose_name': 'Cədvəl',
                'verbose_name_plural': 'Cədvəllər',
                'ordering': ('day_of_week', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson_number', models.IntegerField(verbose_name='Dərs nömrəsi')),
                ('date', models.DateField(verbose_name='Tarix')),
                ('start_time', models.TimeField(verbose_name='Başlama vaxtı')),
                ('end_time', models.TimeField(verbose_name='Bitmə vaxtı')),
                ('topic', models.CharField(blank=True, max_length=300, verbose_name='Mövzu')),
                ('objectives', models.TextField(blank=True, verbose_name='Məqsədlər')),
                ('materials', models.JSONField(blank=True, default=list, verbose_name='Materiallar')),
                ('homework', models.TextField(blank=True, verbose_name='Ev tapşırığı')),
                ('notes', models.TextField(blank=True, verbose_name='Qeydlər')),
                ('video_recording', models.URLField(blank=True, verbose_name='Video yazı')),
                ('status', models.CharField(choices=[('scheduled', 'Planlaşdırılıb'), ('in_progress', 'Davam edir'), ('completed', 'Bitib'), ('cancelled', 'Ləğv olunub')], default='scheduled', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.group', verbose_name='Qrup')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='teachers.teacher', verbose_name='Müəllim')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='schedule.schedule', verbose_name='Cədvəl')),
            ],
            options={
                'verbose_name': 'Dərs',
                'verbose_name_plural': 'Dərslər',
                'ordering': ('date', 'start_time'),
                'unique_together': {('group', 'lesson_number')},
            },
        ),
        migrations.CreateModel(
            name='LessonAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Gəlib'), ('absent', 'Gəlməyib'), ('late', 'Gecikib'), ('excused', 'Üzrlü')], default='absent', max_length=20, verbose_name='Status')),
                ('late_minutes', models.IntegerField(default=0, verbose_name='Gecikmə (dəq)')),
                ('points', models.IntegerField(blank=True, null=True, verbose_name='Bal')),
                ('note', models.TextField(blank=True, verbose_name='Qeyd')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_attendances', to='schedule.lesson', verbose_name='Dərs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_attendances', to='students.student', verbose_name='Tələbə')),
            ],
            options={
                'verbose_name': 'Dərs davamiyyəti',
                'verbose_name_plural': 'Dərs davamiyyətləri',
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]
