# Generated by Django 5.2.5 on 2026-07-16 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Ad')),
                ('start_date', models.DateField(verbose_name='Başlama tarixi')),
                ('end_date', models.DateField(verbose_name='Bitmə tarixi')),
                ('is_current', models.BooleanField(default=False, verbose_name='Cari il')),
            ],
            options={
                'verbose_name': 'Tədris ili',
                'verbose_name_plural': 'Tədris illəri',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='İkon')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Kurs kateqoriyası',
                'verbose_name_plural': 'Kurs kateqoriyaları',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='Ad')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Şəkil')),
                ('duration_weeks', models.IntegerField(default=0, verbose_name='Müddət (həftə)')),
                ('lesson_count', models.IntegerField(default=0, verbose_name='Dərs sayı')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qiymət')),
                ('installment_allowed', models.BooleanField(default=True, verbose_name='Hissə-hissə ödəniş')),
                ('max_installments', models.IntegerField(default=0, verbose_name='Maksimum hissə')),
                ('curriculum', models.JSONField(blank=True, default=list, verbose_name='Tədris proqramı')),
                ('requirements', models.JSONField(blank=True, default=list, verbose_name='Tələblər')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.academicyear', verbose_name='Tədris ili')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='teachers.teacher', verbose_name='Müəllim')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.coursecategory', verbose_name='Kateqoriya')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='Başlıq')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('date', models.DateTimeField(verbose_name='Tarix')),
                ('registration_deadline', models.DateTimeField(verbose_name='Qeydiyyat son tarixi')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qiymət')),
                ('max_participants', models.IntegerField(default=0, verbose_name='Maksimum iştirakçı')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Məkan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='courses.academicyear', verbose_name='Tədris ili')),
            ],
            options={
                'verbose_name': 'Sınaq imtahanı',
                'verbose_name_plural': 'Sınaq imtahanları',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='ExamRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=150, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('message', models.TextField(blank=True, verbose_name='Mesaj')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Qeydiyyat tarixi')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='courses.exam', verbose_name='İmtahan')),
            ],
            options={
                'verbose_name': 'İmtahan qeydiyyatı',
                'verbose_name_plural': 'İmtahan qeydiyyatları',
                'ordering': ('-registered_at',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
                ('type', models.CharField(choices=[('group', 'Qrup'), ('individual', 'Fərdi'), ('intensive', 'İntensiv')], default='group', max_length=20, verbose_name='Tip')),
                ('schedule_text', models.CharField(blank=True, max_length=200, verbose_name='Cədvəl')),
                ('weekdays', models.JSONField(blank=True, default=list, help_text='Seçilmiş günlər', verbose_name='Həftənin günləri')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Başlama tarixi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitmə tarixi')),
                ('max_students', models.IntegerField(default=20, verbose_name='Maksimum tələbə')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Qiymət')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('completed', 'Bitmiş'), ('cancelled', 'Ləğv olunmuş'), ('pending', 'Gözləyir')], default='active', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='courses.academicyear', verbose_name='Tədris ili')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='courses.course', verbose_name='Kurs')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='teachers.teacher', verbose_name='Müəllim')),
            ],
            options={
                'verbose_name': 'Qrup',
                'verbose_name_plural': 'Qruplar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('frozen', 'Dondurulmuş'), ('dropped', 'Ayrılıb'), ('completed', 'Bitirib')], default='active', max_length=20, verbose_name='Status')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Qoşulma tarixi')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Ayrılma tarixi')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_students', to='courses.group', verbose_name='Qrup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_students', to='students.student', verbose_name='Tələbə')),
            ],
            options={
                'verbose_name': 'Qrup tələbəsi',
                'verbose_name_plural': 'Qrup tələbələri',
                'unique_together': {('group', 'student')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(related_name='groups', through='courses.GroupStudent', to='students.student', verbose_name='Tələbələr'),
        ),
    ]
