# Generated by Django 5.2.5 on 2026-07-10 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ('-created_at',), 'verbose_name': 'Audit jurnalı', 'verbose_name_plural': 'Audit jurnalı'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Yaratma'), ('update', 'Yeniləmə'), ('delete', 'Silinmə'), ('login', 'Giriş'), ('logout', 'Çıxış'), ('export', 'İxrac'), ('import', 'İmport'), ('view', 'Baxış')], max_length=20, verbose_name='Əməliyyat'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tarix'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(blank=True, default=dict, verbose_name='Detallar'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP ünvanı'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Sistem'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(max_length=100, verbose_name='Modul'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Obyekt ID'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_repr',
            field=models.CharField(blank=True, max_length=300, verbose_name='Obyekt'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='Brauzer'),
        ),
    ]
