# Generated by Django 5.2.5 on 2026-07-16 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codename', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Ad')),
                ('module', models.CharField(max_length=100, verbose_name='Modul')),
                ('action', models.CharField(max_length=50, verbose_name='Əməliyyat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
            ],
            options={
                'verbose_name': 'İcazə',
                'verbose_name_plural': 'İcazələr',
                'ordering': ('module', 'codename'),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Ad')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('is_system', models.BooleanField(default=False, verbose_name='Sistem rolu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Rollar',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='roles.permission', verbose_name='İcazə')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='roles.role', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Rol icazəsi',
                'verbose_name_plural': 'Rol icazələri',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='roles.role', verbose_name='Rol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'İstifadəçi rolu',
                'verbose_name_plural': 'İstifadəçi rolları',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
