# Generated by Django 5.2.5 on 2026-07-16 09:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=200, unique=True, verbose_name='Açar')),
                ('value', models.JSONField(verbose_name='Dəyər')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('is_public', models.BooleanField(default=False, verbose_name='Açıq')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
            ],
            options={
                'verbose_name': 'Sistem parametri',
                'verbose_name_plural': 'Sistem parametrləri',
                'ordering': ('key',),
            },
        ),
    ]
