# Generated by Django 5.2.5 on 2026-07-16 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson_date', models.DateField(blank=True, null=True, verbose_name='Dərs tarixi')),
                ('lesson_number', models.IntegerField(blank=True, null=True, verbose_name='Dərs nömrəsi')),
                ('status', models.CharField(choices=[('present', 'Gəlib'), ('absent', 'Gəlməyib'), ('late', 'Gecikib'), ('excused', 'Üzrlü')], default='present', max_length=20, verbose_name='Status')),
                ('late_minutes', models.IntegerField(default=0, verbose_name='Gecikmə (dəq)')),
                ('reason', models.TextField(blank=True, verbose_name='Səbəb')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='courses.group', verbose_name='Qrup')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Qeyd edən')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student', verbose_name='Tələbə')),
            ],
            options={
                'verbose_name': 'Davamiyyət',
                'verbose_name_plural': 'Davamiyyətlər',
                'ordering': ('-lesson_date',),
                'unique_together': {('student', 'group', 'lesson_date')},
            },
        ),
    ]
